<?php 

include_once("header.html");
?>

<h1 class="entry-title">Datenlage der Stadt Leipzig</h1>
<div class="entry-content">
  <p>Die Stadt Leipzig hat, wie die meisten Städte in Deutschland eine Seite des statistischen Amtes, auf der man einige Daten zur Stadt finden kann. Das sogenannte Leipzig-Informationssystem (<a href="http://statistik.leipzig.de/" title="LIS" target="_blank">LIS</a>) bietet dabei laut eigener Aussage ein zeitnahes Angebot verschiedener relevanter Daten über die Stadt an. Das Amt für Statistik und Wahlen arbeitet dabei nicht allein, sondern wird von verschiedenen Seiten der Stadt, wie unter anderem dem Stadtplanungsamt, unterstützt. Es besteht die Möglichkeit sowohl Informationen über die ganze Stadt einzuholen, als sich direkt über einen Stadtbezirk oder Ortsteil zu informieren. Auf der Internetseite werden einige Informationen als Dateien zum Download angeboten, darunter auch die statistischen Quartalsberichte und Jahrbücher. Alle anderen veröffentlichten Daten können ebenfalls als Tabellen heruntergeladen werden. In jeder der vorhandenen Rubriken, zu denen unter anderem der Bevölkerungsstand oder die Bautätigkeit zählen, werden Tabellen angezeigt, die teilweise noch durch Diagramme visuell ergänzt werden. Unterstützt wird dieses Bild noch durch eine kleine Anzahl an Lebensbäumen für den Bereich „Bevölkerung“. Diese werden übersichtlich auf der Startseite angeboten. Ebenfalls da zu finden sind die aktuellen Neuerungen der Seite, so dass aktualisierte oder völlig neue Daten schnell gefunden werden können. Im Bereich „Kleinräumige Daten“ erhält man eine schnell Übersicht über Ortsteilgrenzen der Stadt, durch die vorhandene Karte gelangt man direkt auf die vorhandenen Daten, die von Interesse sind. Das Datenangebot selbst ist vielseitig, auch wenn auf Ortsteilebene auf „Kultur und Sport“ oder „Energie und Umwelt“ verzichtet wird, Bereiche die gesamtstädtisch abgedeckt werden. Über ein Bedienfeld kann selbst darüber entschieden werden, die Daten welcher Jahre man sehen möchte, wobei es teilweise bis ins Jahr 2000 zurückverfolgt werden kann und auch sehr aktuell ist, also wenigstens Daten bis zum letzten abgeschlossenen Jahr veröffentlicht sind. Über die Seite des LIS gelangt man auch zu Vergleichsangeboten der Stadt mit Mitteldeutschland und anderen Großstädten, um die betrachteten Daten besser bewerten zu können. Über Links wird auf weitere statistische Angebote, so zum Beispiel des Freistaates, hingewiesen. Auch wird darauf verwiesen, dass sich die Datenveröffentlichung noch im Aufbau befindet und stetig erweitert wird.</p>
  <p>Dies wird auch durch Projekte wie <a href="http://www.einundleipzig.de/" title="EinundLeipzig" target="_blank">einundleipzig</a> oder <a href="http://www.leipzig-data.de/" title="Leipzig Data" target="_blank">Leizig-Data</a> gefördert, welche recherchieren und die Verbreitung neuer Daten fördern und fordern. Leipzig-Data ist eine Plattform, die sich für offene Daten der Stadt einsetzt, also lizensfreien Zugang dazu etablieren möchte. Beide Projekte haben ihren Ursprung in der Universität Leipzig und arbeiten auch miteinander. Die Zusammenarbeit mit der Stadt Leipzig funktioniert dabei in Ordnung. Die Projekte sind bekannt, es wird auch Auskunft gegeben. Dies kann zum Teil allerdings mit Wartezeiten und auch erheblichen Kosten verbunden sein.</p>
  <p>Im Direktvergleich mit Berlin sollte Leipzig das Angebot noch erweitern, alles in allem allerdings ist bereits eine solide Basis geschaffen worden, auf der aufgebaut werden kann und auch wird. Besonders im Bereich OpenData kann aber noch vieles besser gemacht werden, insbesondere da die Initiative dabei nicht von der Stadt, sondern der Universität ausgeht.</p>
  <div class="clear"></div>
</div><!-- .entry-content -->
</body>
</html>
