<?php 

include_once("header.html");
?>

<h1 class="entry-title">Gentrifizierungsprozesse in Leipzig</h1>
<div class="entry-content">
  <p>„Lofts aus Liebe – Investoren vertreiben Bewohner“ behauptet <a href="http://www.spiegel.de/panorama/gentrifizierung-in-leipzig-investoren-vertreiben-bewohner-a-973423.html" title="Spiegel Online" target="_blank">Spiegel Online</a>, „Kann Leipzig Hypezig überleben?“ fragt die <a href="http://www.zeit.de/lebensart/2013-10/leipzig-hypezig-gentrifizierung-wohnkonzepte-stadtentwicklung" title="Zeit" target="_blank">Zeit</a>.</p>
  <blockquote><p>„Die Gentrifizierung (von engl. Gentry: niederer Adel), teils auch: Gentrifikation (von engl. Gentrification), ist ein in der Stadtgeographie angewandter Begriff, der einen sozialen Umstrukturierungsprozess eines Stadtteiles beschreibt. Dabei handelt es sich um Veredelung des Wohnumfelds sowohl durch Veränderung der Bevölkerung, wie in aller Regel auch durch Restaurierungs- und Umbautätigkeit“</p>
    <p style="text-align: right;">(<a href="http://www.fremdwort.de/suchen/bedeutung/Gentrifizierung" target="_blank">fremdwort.de</a> Stand: 25.03.2014)</p>
  </blockquote>
  <p>Soweit lautet eine Definition des viel diskutierten Begriffs der Gentrifizierung. Doch was bedeutet er für die Betroffenen? Und was bedeutet er für Leipzig?</p>
  <p>Es ist nicht zu übersehen, dass sich die Stadt im Wandel befindet. War Leipzig Ende der 1980er Jahre nur als graue Messestadt bekannt, hat sie sich heute zu einer für Touristen, Studenten und Künstler attraktiven Stadt entwickelt. Zwischen den Wintersemestern 1993/94 und 2013/14 stieg die Zahl der Studenten an der <a href="http://www.zv.uni-leipzig.de/fileadmin/user_upload/Service/statistiken/1_Studierendenzahlen_seit_dem_Wintersemester_1993_94.pdf" title="Universität Leipzig" target="_blank">Universität Leipzig</a> von 17.462 auf 28.138 an. Leipzig hat das Interesse junger Menschen in ganz Deutschland geweckt und auch der Zustrom ausländischer Studierender wächst. Als Gründe nach Leipzig zu ziehen werden besonders häufig die, im Vergleich zu anderen Städten, niedrigen Mietpreise, die vielen Parks und  die Kunst- und Kulturszene genannt. Die Stadt bietet ein Lebensgefühl, vermittelt den Charme des Unfertigen und zog mit ihren vielen leerstehenden Fabriken Künstler an, die dort in den letzten zwei Jahrzehnten kreativen Wohnraum, Theater oder Galerien geschaffen haben. So war beispielweise der Leipziger Westen früher ein reines Industriegebiet mit Baumwollspinnereien, Gerbereien und Wäschefabriken. Da die Industrie nach der Wiedervereinigung zunächst brach lag und die Hallen langsam verfielen, interessierte sich niemand weiter für sie. Doch inzwischen werden zunehmend Investoren auf die roten Backsteingebäude aufmerksam. Sie wollen moderne und luxuriöse Wohnfläche schaffen, denn die Nachfrage auf dem Markt ist dank des Bevölkerungszuwachses von Außen stabil. Käufer spekulieren auf einen Boom und deshalb werden viele Wohnungen von Immobilienhändlern aus den alten Bundesländern erworben und dann saniert. Die bisherigen Mieter solcher Wohnungen können die im Anschluss an die Instandsetzung gestiegenen Mieten häufig nicht tragen.  So kommt es zu Binnenwanderung innerhalb der Stadt, ein typisches Merkmal für den Gentrifizierungsprozess. Ähnlich finden diese Veränderungen auch in vielen andern Großstädten wie Berlin, Hamburg oder London statt. Anhand des Londoner Stadtteils Islington untersuchte die britische Soziologin Ruth Glass die Gentrifizierung und beschreibt sie als: </p>
  <blockquote><p>„Den Wechsel von einer statusniedrigeren zu einer statushöheren (finanzkräftigeren) Bewohnerschaft, der oft mit einer baulichen Aufwertung, Veränderungen der Eigentümerstruktur und steigenden Mietpreisen einhergeht.“</p>
    <p style="text-align: right;">(<a href="http://www.difu.de/publikationen/difu-berichte-42011/was-ist-eigentlich-gentrifizierung.html" target="_blank">difu.de</a>)</p>
  </blockquote>
  <p>Damit spricht sie auch eine der positiven Auswirkungen des Prozesses an. Zunächst werden durch die Sanierungen historische Gebäude in Stand gesetzt und erhalten. So stehen einige der ehemaligen Fabriken in Leipzig heute unter Denkmalschutz. Damit korrespondiert auch eine optische Aufwertung des Stadtbildes, welches wiederum Touristen, Studenten oder weitere Käufer anlockt. Für die einkommensstärkere Bevölkerung wird durch die Restaurierung der Altbauwohnungen ein angenehmes Wohnambiente geschaffen. Da in Folge zunehmend wohlhabendere Schichten bestimmte Bezirke bevölkern, verschwinden aus stadtentwicklungspolitischer Sicht zum Teil problematische Nachbarschaften. Beispielsweise galt der Stadtteil Kreuzberg in Berlin lange Zeit als unsicher und ist inzwischen zu einem angesagten Viertel avanciert. Der Zuwachs einkommensstärkerer Bevölkerung hat auch wirtschaftliche Folgen. Einerseits, steigt die Kaufkraft in bestimmten Stadtteilen, was dazu führt, dass sich neue Geschäfte ansiedeln, andererseits verdrängen diese, das bisherige Kleingewerbe. Ein ebenso bedeutsamer Effekt zeigt sich bei den öffentlichen Haushalten. Denn durch die Gentrifizierung wächst zwar die Kaufkraft einer Stadt, gleichzeitig steigen aber die Ausgaben der öffentlichen Hand für die Absicherung des Wohnens der verdrängten Bevölkerungsschichten.</p>
  <p>So stehen sich zwei Positionen gegenüber, denn Verdrängung ist dem Begriff der Gentrifizierung inhärent. Der Zuwachs von Außen hat, auch in Leipzig, eine Umstrukturierung der bestehenden Bevölkerung zur Folge. Die Mieten steigen, die Ortsteile verändern sich – optisch, wie auch in ihrer Bevölkerungszusammensetzung. Grund genug sich weiter mit dem Prozess der Gentrifizierung zu beschäftigen. Mit seinen Schattenseiten und den Chancen dieses Wandels.</p>
  <div class="clear"></div>
</div><!-- .entry-content -->
</body>
</html>
