<?php 

include_once("header.html");
?>

<h1 class="entry-title">Weitere Projekte</h1>
<div class="entry-content">
  <p>Das Gentri-14 Projekt, bzw. <a href="http://www.einundleipzig.de" target="_blank">einundleipzig</a>, sind nicht die einzigen Projekte in Deutschland, die Gentrifizierungsprozesse beobachten. Insbesondere in Berlin, der deutschen Hauptstadt der Gentrifizierung, setzen sich Menschen mit diesem Thema auseinander. Da diese Prozesse denen in Leipzig zeitlich voraus gehen, entstanden auch die entsprechenden Projekte früher.</p>
  <p>In Berlin angesiedelt und am bekanntesten sind die von Andrej Holm verantwortete GentriMap und der Gentrificationblog. Der Grundgedanke beider Websites ist die Vermittlung zwischen wissenschaftlicher Debatte und realer Erfahrungswelt. Die GentriMap verdeutlicht abstrakte Daten, die Einfluss auf die Gentrifizierung haben. Diese Zahlen, beispielsweise soziodemografische Angaben wie Alter von Anwohnern, werden in einer Karte der Berliner Stadtviertel farblich dargestellt. Das interaktive Design der Karte und eine zeitliche Spannbreite von 4 Jahren ermöglichen es außerdem, mehrere Daten zu verknüpfen. So kann der Betrachter Schlüsse ziehen. </p>
  <p>Der Gentrificationblog setzt auf Neuigkeiten, die Anwohnern und interessierten Lesern zur Verfügung gestellt werden. Im Fokus stehen dabei Bauvorhaben und die Mobilisierung der Stadtteile. Über Artikel, Videos und Veranstaltungshinweise werden Themen der Berliner Gentrifizierungsprozesse aufbereitet. Sowohl der Gentrificationblog als auch die GentriMap verstehen sich dabei als journalistische Projekte. Durch die Verwendung amtlicher Daten und Mitteilungen werden Initiativen der OpenData-Bewegung, also das Bemühen um freizugängliche Darstellungen amtlicher Daten, unterstützt. </p>
  <p>Diesen Anspruch hat auch einundleipzig. Amtliche Daten, die zwar teilweise öffentlich zugänglich sind, sollen übersichtlich, verständlich und offen für alle Interessierten sein. Ähnlich wie bei der GentriMap zeigen Karten Entwicklungen innerhalb Leipzigs auf, die im Kontext von Gentrifizierung stehen. Dabei geht auch einundleipzig journalistisch und wissenschaftlich vor. Eine Erweiterung zu den Berliner Projekten ist jedoch der Bezug auf individuelle Geschichten. Betroffene Leipziger können dabei einerseits erzählen, wie sie Veränderung in ihrem Viertel wahrnehmen. Andererseits können verschiedene Karten durch den eigenen Wissensschatz erweitert werden, indem man beispielsweise ein Wächterhaus einträgt, das noch nicht verzeichnet ist. </p>
  <p>Damit ist einundleipzig im Bereich Gentrifizierung in Leipzig einmalig. Es gibt zwar verschiedene Ansätze in Leipzig, doch bisher verknüpft keiner die existierenden Daten so kompakt. Unter diesen Ansätzen, sind Arbeiten des Helmholtz-Zentrums für Umweltforschung hervorzuheben. Hier gibt es mehrere Forschungsarbeiten, die relevante Daten im Zusammenhang mit Gentrifizierung erhoben haben. Diese sind jedoch nicht öffentlich. Auch die Stadt Leipzig steht der Gentrifizierung aufmerksam gegenüber. Im Stadtentwicklungskonzept Leipzig 2020 fließen Überlegungen und empirische Ergebnisse bezüglich der Gentrifizierung ein. Viele dieser erhobenen Daten aus Forschungen des Helmholtz-Zentrums oder der Stadt Leipzig kommen bei einundleipzig zusammen und erweitern das Bild, das so von den Gentrifizierungsprozessen in Leipzig gezeichnet werden kann.</p>
  <div class="clear"></div>
</div><!-- .entry-content -->
</body>
</html>
